---
version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: domain-management
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./src/domainManagementUI:/app
    networks:
      - frontend
    env_file:
      - .env
networks:
  frontend:
    name: domain_management_frontend
